### ISSUE TITLE
Typo on WebGL2 Picking page

### ISSUE THREAD

**Issue by mrspeaker** [gfxfundamentals/webgl2-fundamentals#141]
Minor issue on the [*WebGL2 Picking*](https://webgl2fundamentals.org/webgl/lessons/webgl-picking.html) page. In the *Clicking on an Object* section it says:

"So, let's start with the last example from the article on [drawing multiple](https://webgl2fundamentals.org/webgl/lessons/webgl-drawing-multiple-things.html) things that draws 200 things."

The examples in the linked page only show how to draw 3 things (not 200). It would be good to update this, because it's using the "200 things" as the base code for picking - but I'm not sure if the code really is the same (if it is the same, then just change "200" to "3"!).

**Comment by greggman** [comment]
Thanks! I guess I didn't include the 200 object example in WebGL2. (it's in [the WebGL1 page](https://webgl2fundamentals.org/webgl/lessons/webgl-drawing-multiple-things.html)). I'll have to fix that

**Comment by greggman** [comment]
So I fixed the article the picking article was referencing so it has a 200 object example

https://webgl2fundamentals.org/webgl/lessons/webgl-drawing-multiple-things.html

**Comment by mrspeaker** [comment]
Awesome! That page is way cooler with 200 objects too ;)
