### ISSUE TITLE
texture2d used instead of texture in sample code shader at the top of less code more fun

### ISSUE THREAD

**Issue by johnstrickermayo** [gfxfundamentals/webgl2-fundamentals#158]
**Describe the bug**
The sample fragment shader code at the top doesn't match the fragment shader code used in the running example.

These are fantastic tutorials by the way, thank you so much!

**To Reproduce**
1. Go to https://webgl2fundamentals.org/webgl/lessons/webgl-less-code-more-fun.html
2. look at the first fragment shader code and note that  
```
void main() {
   vec4 diffuseColor = texture2D(u_diffuse, v_texCoord);
```

is not the same as the fragment shader in the first running example:
```
  vec4 diffuseColor = texture(u_diffuse, v_texCoord);
```

if you use the code shown first for the shader, it won't compile due to a type mismatch.

**Comment by greggman** [comment]
Thanks!

https://github.com/gfxfundamentals/webgl2-fundamentals/commit/f784f3691085a553784b9ddbe5c3e6249f25c5e7
