### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by alicialics** [gfxfundamentals/webgl2-fundamentals#185]
**Describe the bug**
Tinypic links in this article are broken.
https://github.com/gfxfundamentals/webgl2-fundamentals/blob/master/webgl/lessons/webgl-qna-how-to-make-webgl-canvas-transparent.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by greggman** [comment]
[fixed](https://github.com/gfxfundamentals/webgl2-fundamentals/commit/0b8d37037df5570d6e1dde4c89580938a22db23f)
