### ISSUE TITLE
The front page looks bad on amd RX460

### ISSUE THREAD

**Issue by manueldun** [gfxfundamentals/webgl2-fundamentals#58]
I was reading the webgl 2 fundamentals normally and I thought the frontpage looked normal in my desktop machine... then I tried the frontpage on my laptop and realized that it looked better: the floating meshes (2s) had black spots in them that make look kind of bad in the desktop machine.

My desktop machine (where the frontpage looked bad) is:
cpu: Intel 930 i7
gpu: Amd RX460
ram: 8GB
Os: Windows 10 and ubuntu linux (yes both)
Browser: Chrome and Firefox (yes both, in both OSs)

My laptop
OS: Windows 10
Browser: Chrome and Firefox
cpu Intel core i3-4000M
gpu: integrated
ram: 2GB

Screenshot from my desktop machine:
![frontpage desktop](https://user-images.githubusercontent.com/7586239/62584849-412a5d00-b884-11e9-8345-af9b9ccf44f4.png)

![laptop frontpage](https://user-images.githubusercontent.com/7586239/62585203-9d41b100-b885-11e9-8215-31308cca4f69.png)

I know it has to do with my hardware but i want to know how to fix it and this is the best place I can find to get a fix, and is weird that the problem persist in all systems (browsers and OSs).

**Comment by greggman** [comment]
try it now - might have to clear your cache or turn it off in your browser's dev tools

I don't have an AMD to test on unfortunately

**Comment by manueldun** [comment]
Now it works, thanks.

**Comment by greggman** [comment]
Thanks for reporting it. It was a pow(negativeNumber, ...) issue which I know better but didn't notice.
