### ISSUE TITLE
the gh pages is broken!

### ISSUE THREAD

**Issue by yifan18** [gfxfundamentals/webgl2-fundamentals#86]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6284047/99476795-2eaa3900-298c-11eb-9497-9b3c6f157cf0.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by greggman** [comment]
thanks. fixed
